spring:
  application:
    name: db-Router
router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 2
      routerKey: userId
      list: db01,db02
      db01:
        url: 123213
      db02:
        url: 2313